[kata]
name = "neetcode_group_anagrams"
category = "exercises"
base_difficulty = 2
description = """Group Anagrams (LeetCode 49)

Given an array of strings strs, group the anagrams together. You can return the answer in any order.

Example 1:
Input: strs = ["eat","tea","tan","ate","nat","bat"]
Output: [["bat"],["nat","tan"],["ate","eat","tea"]]

Example 2:
Input: strs = [""]
Output: [[""]]

Constraints:
- 1 <= strs.length <= 10^4
- 0 <= strs[i].length <= 100
"""
dependencies = ["neetcode_valid_anagram"]
