[kata]
name = "neetcode_min_stack"
category = "exercises"
base_difficulty = 2
description = """Min Stack (LeetCode 155)

Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.

Implement the MinStack class:
- MinStack() initializes the stack object
- void push(int val) pushes the element val onto the stack
- void pop() removes the element on top of the stack
- int top() gets the top element of the stack
- int getMin() retrieves the minimum element in the stack

Example 1:
Input: ["MinStack","push","push","push","getMin","pop","top","getMin"]
[[],[-2],[0],[-3],[],[],[],[]]
Output: [null,null,null,null,-3,null,0,-2]

Constraints:
- -2^31 <= val <= 2^31 - 1
- pop, top and getMin will always be called on non-empty stacks
"""
dependencies = []
