[kata]
name = "neetcode_product_except_self"
category = "exercises"
base_difficulty = 2
description = """Product of Array Except Self (LeetCode 238)

Given an integer array nums, return an array answer such that answer[i] is equal to
the product of all the elements of nums except nums[i].

You must write an algorithm that runs in O(n) time and without using the division operation.

Example 1:
Input: nums = [1,2,3,4]
Output: [24,12,8,6]

Example 2:
Input: nums = [-1,1,0,-3,3]
Output: [0,0,9,0,0]

Constraints:
- 2 <= nums.length <= 10^5
- -30 <= nums[i] <= 30
"""
dependencies = []
