[kata]
name = "neetcode_meeting_rooms_ii"
category = "exercises"
base_difficulty = 2
description = """Meeting Rooms II (LeetCode 253)

Given an array of meeting time intervals intervals where intervals[i] = [starti, endi], return
the minimum number of conference rooms required.

Example 1:
Input: intervals = [[0,30],[5,10],[15,20]]
Output: 2

Example 2:
Input: intervals = [[7,10],[2,4]]
Output: 1

Constraints:
- 1 <= intervals.length <= 10^4
- intervals[i].length == 2
- 0 <= starti < endi <= 10^6
"""
dependencies = ["neetcode_meeting_rooms"]
