[kata]
name = "neetcode_find_min_rotated"
category = "exercises"
base_difficulty = 2
description = """Find Minimum in Rotated Sorted Array (LeetCode 153)

Suppose an array of length n sorted in ascending order is rotated between 1 and n times.
Given the sorted rotated array nums of unique elements, return the minimum element of this array.

Example 1:
Input: nums = [3,4,5,1,2]
Output: 1

Example 2:
Input: nums = [4,5,6,7,0,1,2]
Output: 0

Constraints:
- n == nums.length
- 1 <= n <= 5000
- -5000 <= nums[i] <= 5000
- All integers of nums are unique
"""
dependencies = ["neetcode_binary_search"]
